# Generated by Django 5.1.3 on 2025-05-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_user_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('cod', 'Cash on Delivery'), ('Square', 'Square')], max_length=50, unique=True),
        ),
    ]
