databases:
  - name: swiftcart-db
    plan: free
    databaseName: swiftcart
    user: swiftcart_user

services:
  - type: web
    plan: free
    name: swiftcart
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn core.wsgi:application --bind 0.0.0.0:8000'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: swiftcart-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
