# Generated by Django 5.1.3 on 2025-05-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuplog',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
