# Generated by Django 5.1.3 on 2025-05-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_signuplog_email_otp_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
